version: '3.9'

volumes:
  db-volume:

services:
  php:
    build: .docker/php
    ports:
      - '127.0.0.1:${APP_PORT:-80}:80'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - '.:/app'
    working_dir: /app
    command: composer start
  db:
    image: postgres:16-alpine
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - 'db-volume:/var/lib/postgresql/data'
      - '.docker/db/scheme.sql:/docker-entrypoint-initdb.d/00-scheme.sql:ro'
      - '.docker/db/seed.sql:/docker-entrypoint-initdb.d/10-seed.sql:ro'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
